In [203]:
import numpy as np
import math
import scipy.io as sio


In [204]:
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [205]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [206]:
d = {}
mat = sio.loadmat("ex3data1.mat")

In [207]:
X = mat['X']

In [224]:
mat

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011',
 '__version__': '1.0',
 '__globals__': [],
 'X': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'y': array([[10],
        [10],
        [10],
        ...,
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)}

In [208]:
X.shape

(5000, 400)

In [209]:
y = mat['y']

In [210]:
y.shape

(5000, 1)

In [211]:
lst=[math.sin(i) for i in range(1,17)]
lst

[0.8414709848078965,
 0.9092974268256817,
 0.1411200080598672,
 -0.7568024953079282,
 -0.9589242746631385,
 -0.27941549819892586,
 0.6569865987187891,
 0.9893582466233818,
 0.4121184852417566,
 -0.5440211108893699,
 -0.9999902065507035,
 -0.5365729180004349,
 0.4201670368266409,
 0.9906073556948704,
 0.6502878401571169,
 -0.2879033166650653]

In [212]:
X = np.array([math.sin(i) for i in range(1,17)]).reshape((8, 2), order='F')

In [213]:
X.shape

(8, 2)

Fill columns first

In [214]:
Theta1 = np.array([math.sin(x) for x in np.linspace(0,5.5,12)]).reshape((4, 3), order='F')

In [215]:
Theta1

array([[ 0.        ,  0.90929743, -0.7568025 ],
       [ 0.47942554,  0.59847214, -0.97753012],
       [ 0.84147098,  0.14112001, -0.95892427],
       [ 0.99749499, -0.35078323, -0.70554033]])

In [216]:
Theta2 = np.array([math.sin(x) for x in np.linspace(0,5.7,20)]).reshape((4, 5), order='F')

In [217]:
Theta2

array([[ 0.        ,  0.93203909,  0.67546318, -0.44252044, -0.99616461],
       [ 0.29552021,  0.99749499,  0.42737988, -0.68776616, -0.92581468],
       [ 0.56464247,  0.97384763,  0.14112001, -0.87157577, -0.77276449],
       [ 0.78332691,  0.86320937, -0.15774569, -0.97753012, -0.55068554]])

In [218]:
X

array([[ 0.84147098,  0.41211849],
       [ 0.90929743, -0.54402111],
       [ 0.14112001, -0.99999021],
       [-0.7568025 , -0.53657292],
       [-0.95892427,  0.42016704],
       [-0.2794155 ,  0.99060736],
       [ 0.6569866 ,  0.65028784],
       [ 0.98935825, -0.28790332]])

In [219]:
np.insert(X, 0, 1, axis=1)

array([[ 1.        ,  0.84147098,  0.41211849],
       [ 1.        ,  0.90929743, -0.54402111],
       [ 1.        ,  0.14112001, -0.99999021],
       [ 1.        , -0.7568025 , -0.53657292],
       [ 1.        , -0.95892427,  0.42016704],
       [ 1.        , -0.2794155 ,  0.99060736],
       [ 1.        ,  0.6569866 ,  0.65028784],
       [ 1.        ,  0.98935825, -0.28790332]])

In [220]:
Theta2

array([[ 0.        ,  0.93203909,  0.67546318, -0.44252044, -0.99616461],
       [ 0.29552021,  0.99749499,  0.42737988, -0.68776616, -0.92581468],
       [ 0.56464247,  0.97384763,  0.14112001, -0.87157577, -0.77276449],
       [ 0.78332691,  0.86320937, -0.15774569, -0.97753012, -0.55068554]])

In [221]:
vectorized_sigmoid = np.vectorize(sigmoid)


In [222]:
def predict(theta1, theta2, X):
    m = X.size
    print(f"theta1.shape={theta1.shape}")
    print(f"theta1=\n{theta1}")
    
    print(f"theta2.shape={theta2.shape}")
    print(f"theta2=\n{theta2}")


    num_rows, num_cols = X.shape
    print(f"Size={num_rows}")
    a1 = np.insert(X, 0, 1, axis=1)
    print(f"X={a1}")
    z2 = np.matmul(a1, np.transpose(Theta1))
    print(f"z2={z2}")
    a2 = vectorized_sigmoid(z2)
    
    a2.shape
    print(f"a2.shape={a2.shape}")

    print(f"a2={a2}")
    a2 = np.insert(a2, 0, 1, axis=1)
    print(f"a2={a2}")

    a3 = np.matmul(a2, np.transpose(Theta2))
    print(f"a3={a3}")
    
    a3 = vectorized_sigmoid(a3)
    print(f"sigmoid(a3)=\n{a3}")

    p = a3.argmax(axis=1)
    p = p + 1
    print(f"p={p}")
#     z3 = np.array(map(sigmoid, z2))
#     print(f"z3={z4}")

In [223]:
predict(Theta1,Theta2,X)

theta1.shape=(4, 3)
theta1=
[[ 0.          0.90929743 -0.7568025 ]
 [ 0.47942554  0.59847214 -0.97753012]
 [ 0.84147098  0.14112001 -0.95892427]
 [ 0.99749499 -0.35078323 -0.70554033]]
theta2.shape=(4, 5)
theta2=
[[ 0.          0.93203909  0.67546318 -0.44252044 -0.99616461]
 [ 0.29552021  0.99749499  0.42737988 -0.68776616 -0.92581468]
 [ 0.56464247  0.97384763  0.14112001 -0.87157577 -0.77276449]
 [ 0.78332691  0.86320937 -0.15774569 -0.97753012 -0.55068554]]
Size=8
X=[[ 1.          0.84147098  0.41211849]
 [ 1.          0.90929743 -0.54402111]
 [ 1.          0.14112001 -0.99999021]
 [ 1.         -0.7568025  -0.53657292]
 [ 1.         -0.95892427  0.42016704]
 [ 1.         -0.2794155   0.99060736]
 [ 1.          0.6569866   0.65028784]
 [ 1.          0.98935825 -0.28790332]]
z2=[[ 0.4532551   0.58016425  0.56502896  0.41155487]
 [ 1.23853834  1.55541174  1.49146609  1.06235753]
 [ 0.88511514  1.54140248  1.82030072  1.65352587]
 [-0.28207884  0.55101651  1.24920381  1.64154244]
 [-1.